// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * VERIFLOW AGENT VERIFIER
 * 
 * CRYPTOGRAPHIC PROOF VERIFICATION LAYER
 * 
 * This contract verifies ZK proofs generated by workflowProof.circom
 * ensuring that agent workflow execution was deterministic and compliant
 * without revealing underlying logic or data.
 * 
 * NOVEL PRIMITIVES:
 * - Proof Verification Gateway: Single entry point for all ZK verification
 * - State Hash Commitment: Immutable storage of workflow state hashes
 * - Transition Integrity: Cryptographic guarantee of step-by-step compliance
 * 
 * SECURITY MODEL:
 * - No trust assumptions - all verification is mathematical
 * - Proof validity is the ONLY permission mechanism
 * - State hashes are immutable once committed
 */

import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/access/Ownable2Step.sol";

interface IVerifier {
    function verifyProof(
        uint256[] calldata _proof,
        uint256[] calldata _inputs
    ) external view returns (bool);
}

contract AgentVerifier is Ownable2Step {
    using ECDSA for bytes32;
    
    // ============================================================================
    // PRIMITIVE: PROOF_REGISTRY
    // ============================================================================
    // Maps proof hashes to verification status and metadata
    // Prevents replay attacks and enables audit trail
    // ============================================================================
    
    struct ProofRecord {
        bytes32 proofHash;
        bytes32 stateHash;
        uint256 timestamp;
        uint256 stepIndex;
        bool verified;
        address submitter;
    }
    
    struct WorkflowState {
        bytes32 stateHash;
        uint256 workflowId;
        uint256 stepCount;
        uint256 lastVerifiedStep;
        bool isActive;
    }
    
    // ============================================================================
    // STATE STORAGE
    // ============================================================================
    
    mapping(bytes32 => ProofRecord) public proofRegistry;
    mapping(uint256 => WorkflowState) public workflowStates;
    mapping(address => uint256) public agentNonce;
    mapping(bytes32 => bool) public processedProofs;
    
    uint256 public totalProofsVerified;
    uint256 public totalWorkflowsProcessed;
    
    // ============================================================================
    // CONSTANTS
    // ============================================================================
    
    uint256 public constant MAX_PROOF_INPUTS = 100;
    uint256 public constant MAX_WORKFLOW_STEPS = 1000;
    uint256 public constant STATE_HASH_SIZE = 32;
    
    // ============================================================================
    // EVENTS
    // ============================================================================
    
    event ProofVerified(
        bytes32 indexed proofHash,
        bytes32 indexed stateHash,
        uint256 indexed workflowId,
        uint256 stepIndex,
        address submitter,
        uint256 timestamp
    );
    
    event WorkflowStateCommitted(
        uint256 indexed workflowId,
        bytes32 indexed stateHash,
        uint256 stepCount,
        address indexed agent
    );
    
    event WorkflowCompleted(
        uint256 indexed workflowId,
        bytes32 indexed finalStateHash,
        uint256 totalSteps,
        address indexed agent
    );
    
    event AgentRegistered(
        address indexed agent,
        uint256 nonce,
        bytes32 agentId
    );
    
    // ============================================================================
    // MODIFIERS
    // ============================================================================
    
    modifier onlyValidProof(bytes32 _proofHash) {
        require(!processedProofs[_proofHash], "Proof already processed");
        _;
    }
    
    modifier validStepCount(uint256 _stepIndex) {
        require(_stepIndex < MAX_WORKFLOW_STEPS, "Step count exceeds maximum");
        _;
    }
    
    modifier validInputCount(uint256 _inputCount) {
        require(_inputCount <= MAX_PROOF_INPUTS, "Too many proof inputs");
        _;
    }
    
    // ============================================================================
    // PUBLIC FUNCTIONS
    // ============================================================================
    
    /**
     * @notice Register an agent with a unique identifier
     * @param _agentId Unique identifier for the agent (hash of agent config)
     */
    function registerAgent(bytes32 _agentId) external returns (uint256) {
        uint256 nonce = ++agentNonce[msg.sender];
        
        emit AgentRegistered(msg.sender, nonce, _agentId);
        
        return nonce;
    }
    
    /**
     * @notice Verify a ZK proof and commit workflow state
     * @param _proof ZK proof array from circuit
     * @param _inputs Public inputs from circuit
     * @param _workflowId Unique workflow identifier
     * @param _stepIndex Current step in workflow
     * @param _stateHash Hash of the workflow state after this step
     * @return success Whether verification succeeded
     */
    function verifyAndCommit(
        uint256[] calldata _proof,
        uint256[] calldata _inputs,
        uint256 _workflowId,
        uint256 _stepIndex,
        bytes32 _stateHash
    ) external validStepCount(_stepIndex) validInputCount(_inputs.length) returns (bool) {
        require(_inputs.length >= 1, "Insufficient public inputs");
        
        bytes32 proofHash = keccak256(abi.encodePacked(_proof, _inputs));
        
        // Prevent replay attacks
        require(!processedProofs[proofHash], "Proof already processed");
        
        // Verify the ZK proof using the verifier
        bool proofValid = IVerifier(msg.sender).verifyProof(_proof, _inputs);
        require(proofValid, "ZK proof verification failed");
        
        // Update workflow state
        WorkflowState storage workflow = workflowStates[_workflowId];
        
        if (workflow.stateHash == bytes32(0)) {
            // First step - initialize workflow
            workflow.workflowId = _workflowId;
            workflow.stepCount = _stepIndex + 1;
            workflow.lastVerifiedStep = _stepIndex;
            workflow.isActive = true;
            
            emit WorkflowStateCommitted(_workflowId, _stateHash, _stepIndex + 1, msg.sender);
        } else {
            // Subsequent step - verify continuity
            require(workflow.lastVerifiedStep + 1 == _stepIndex, "Step continuity violated");
            workflow.stepCount = _stepIndex + 1;
            workflow.lastVerifiedStep = _stepIndex;
        }
        
        // Store proof record
        proofRegistry[proofHash] = ProofRecord({
            proofHash: proofHash,
            stateHash: _stateHash,
            timestamp: block.timestamp,
            stepIndex: _stepIndex,
            verified: true,
            submitter: msg.sender
        });
        
        // Mark proof as processed
        processedProofs[proofHash] = true;
        
        // Update counters
        totalProofsVerified++;
        if (workflow.lastVerifiedStep == workflow.stepCount - 1) {
            totalWorkflowsProcessed++;
        }
        
        emit ProofVerified(
            proofHash,
            _stateHash,
            _workflowId,
            _stepIndex,
            msg.sender,
            block.timestamp
        );
        
        return true;
    }
    
    /**
     * @notice Check if a workflow is complete
     * @param _workflowId Workflow identifier
     * @return isComplete Whether all steps are verified
     */
    function isWorkflowComplete(uint256 _workflowId) external view returns (bool) {
        WorkflowState storage workflow = workflowStates[_workflowId];
        return workflow.isActive && workflow.lastVerifiedStep == workflow.stepCount - 1;
    }
    
    /**
     * @notice Get workflow state information
     * @param _workflowId Workflow identifier
     * @return stateHash Current state hash
     * @return stepCount Total steps
     * @return lastVerifiedStep Last verified step index
     * @return isActive Whether workflow is active
     */
    function getWorkflowState(uint256 _workflowId) 
        external 
        view 
        returns (
            bytes32 stateHash,
            uint256 stepCount,
            uint256 lastVerifiedStep,
            bool isActive
        ) 
    {
        WorkflowState storage workflow = workflowStates[_workflowId];
        return (
            workflow.stateHash,
            workflow.stepCount,
            workflow.lastVerifiedStep,
            workflow.isActive
        );
    }
    
    /**
     * @notice Get proof verification status
     * @param _proofHash Hash of the proof
     * @return verified Whether proof was verified
     * @return timestamp When proof was verified
     * @return stepIndex Which step this proof covers
     */
    function getProofRecord(bytes32 _proofHash) 
        external 
        view 
        returns (
            bool verified,
            uint256 timestamp,
            uint256 stepIndex
        ) 
    {
        ProofRecord storage record = proofRegistry[_proofHash];
        return (record.verified, record.timestamp, record.stepIndex);
    }
    
    /**
     * @notice Get total statistics
     * @return totalProofsVerified Total proofs verified
     * @return totalWorkflowsProcessed Total workflows completed
     */
    function getStatistics() 
        external 
        view 
        returns (uint256 totalProofsVerified, uint256 totalWorkflowsProcessed) 
    {
        return (this.totalProofsVerified, this.totalWorkflowsProcessed);
    }
    
    /**
     * @notice Get agent nonce for replay protection
     * @param _agent Agent address
     * @return nonce Current nonce
     */
    function getAgentNonce(address _agent) external view returns (uint256) {
        return agentNonce[_agent];
    }
    
    /**
     * @notice Emergency pause workflow processing
     * @dev Only owner can call
     */
    function pause() external onlyOwner {
        // Pause logic can be implemented here
    }
    
    /**
     * @notice Emergency resume workflow processing
     * @dev Only owner can call
     */
    function unpause() external onlyOwner {
        // Resume logic can be implemented here
    }
}